//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayMentRESTService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDescription
    {
        public int ProductDesId { get; set; }
        public string ProductId { get; set; }
        public string ProdDetails { get; set; }
    }
}
